# Blueprint configuration file for ACT3 Project Tool
kind: Blueprint
apiVersion: project.act3-ace.io/v1beta1

# List of additional inputs for use in this Blueprint
inputs:
    - key: projectType
      description: "Type of Project"
      default: '{{.meta.name | kebabcase}}'
      required: true
      options:
        - Go
        - Python
    - key: modulePath
      description: Go module path for the project
      default: |-
          {{with .meta.repository}}{{ . | trimPrefix "https://" | trimSuffix ".git" }}{{end}}
      priority: 1
    - key: withGoreleaser
      description: Release with goreleaser
      default: "no"
      options:
        - "no"
        - "yes"
      priority: 1
    - key: executableName
      description: Name of the Go CLI's executable
      default: "{{.meta.name}}"
      priority: 1


# List of conditions to exclude paths when rendering this Blueprint
# Non-empty conditions result in the path being excluded
ignore:
  - path: ".golangci.yaml"
    if: "{{ne .inputs.ProjectType Go}}"
  - path: ".goreleaser.yaml"
    if: "{{and (ne .inputs.ProjectType Go) (ne .inputs.withGoreleaser yes)}}"

# Configure templating in this Blueprint
templating: {}

# Configure project linting with this Blueprint
lint: {}

# Edit configuration:        act3-pt bputil edit
# Test Blueprint rendering:  act3-pt bputil test
# View templating reference: act3-pt bputil reference

