# Blueprint configuration file for ACT3 Project Tool
kind: Blueprint
apiVersion: project.act3-ace.io/v1beta1

# List of additional inputs for use in this Blueprint
inputs:
    # general repository information
    - key: host
      description: "Release target host: github.com, gitlab.com, or a private gitlab host"
      required: true
      default: |-
          {{with .meta.repository}}{{ ( . | trimPrefix "https://" | trimSuffix ".git" | splitn "/" 2 )._0 }}{{end}}
    - key: projectType
      description: "Type of Project"
      required: true
      default: Go
      options:
        - Go
        - Python
    # goreleaser supports both go and python, but python is in alpha
    - key: includeGoreleaser
      description: "Release with goreleaser (go only at this time)"
      priority: 1
      default: "disabled"
      options:
        - "disabled"
        - "enabled"
    # go specific config
    - key: executableName
      description: "Name of the Go CLI's executable"
      priority: 1
    - key: includeDockerPublish
      description: "Publish container image using Dockerfile"
      priority: 0
      default: "disabled"
      options:
        - "disabled"
        - "enabled"
    - key: helmChartDir
      description: "Version and publish helm chart"
      priority: 1
      default: ""

# List of conditions to exclude paths when rendering this Blueprint
# Non-empty conditions result in the path being excluded
ignore:
  - path: .goreleaser.yaml
    if: '{{if (and (eq .inputs.includeGoreleaser "enabled") (eq .inputs.projectType "Go"))}}{{else}}disabled{{end}}'

# Configure templating in this Blueprint
templating: {}

# Configure project linting with this Blueprint
lint: {}

# Edit configuration:        act3-pt bputil edit
# Test Blueprint rendering:  act3-pt bputil test
# View templating reference: act3-pt bputil reference

