# Project configuration file for ACT3 Project Tool
kind: Project
apiVersion: project.act3-ace.io/v1beta1

# List of Blueprints configured for this project
blueprints:
    - ref: https://github.com/act3-ai/blueprint-release.git
      inputs:
        executableName:
        helmChartDir:
        host: github.com
        includeDockerPublish: disabled
        includeGoreleaser: disabled
        projectType: Other

# Edit configuration interactively:
#   Edit metadata:         act3-pt edit
#   Edit CI config:        act3-pt ci edit
#   Edit Blueprint config: act3-pt blueprint edit
# Manage Blueprints:
#   Add Blueprints:  act3-pt blueprint add
#   Update versions: act3-pt blueprint update
# Use CI/CD:
#   Set up CI/CD:  act3-pt ci setup
#   Run pipelines: act3-pt ci run
