version: 2

builds:
  - id: {{.inputs.executableName}}
    binary: {{.inputs.executableName}}
    goos:
      - linux
      - darwin
      # - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.build={{.Version}}
    env:
      - CGO_ENABLED=0
      - GOFIPS140=latest
    main: ./cmd/{{.inputs.executableName}}/

archives:
  - id: {{.inputs.executableName}}-archives
    ids:
      - {{.inputs.executableName}}
    formats: ["tar.gz"]
    builds_info:
      mode: 755
    name_template: `"`{{.inputs.executableName}}`"-v{{ .Version }}-{{ .Os }}-{{ .Arch }}`
    files:
      - LICENSE
      - src: releases/v{{ .Version }}.md
        strip_parent: true

release:
  github:
    owner: act3-ai
    name: data-tool
  ids:
    - {{.inputs.executableName}}-archives
  make_latest: envOrDefault "RELEASE_LATEST" "true"
  mode: replace # if we need to re-release, don't duplicate the release notes
  skip_upload: false

checksum:
  name_template: "ace-dt-v{{ .Version }}-checksums.txt"
  algorithm: sha256
  ids:
    - {{.inputs.executableName}}-archives
  disable: false
